admin@raspberrypi:~/libraries/RPLidar/build/linux/arm64-v8a/release $ ./test
Opened serial: 1
[2023-12-07 23:28:13.745] [debug] Command sent:
0000: a5 50
[2023-12-07 23:28:13.746] [debug] Received descriptor:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Descriptor length mismatch : 0
Aborted
admin@raspberrypi:~/libraries/RPLidar/build/linux/arm64-v8a/release $ python
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rplidar import RPLidar
>>>
>>> lidar = RPLidar('/dev/ttyUSB0')
>>>
>>> logging.basicConfig(level=logging.DEBUG)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'logging' is not defined
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>>
>>> info = lidar.get_info()
DEBUG:rplidar:Command sent: ['0xa5', '0x50']
DEBUG:rplidar:Received descriptor: ['0xa5', '0x5a', '0x14', '0x0', '0x0', '0x0', '0x4']
DEBUG:rplidar:Trying to read response: 20 bytes
DEBUG:rplidar:Received data: ['0x28', '0x19', '0x1', '0x5', '0xdf', '0xf4', '0x9a', '0xf2', '0xc1', '0xea', '0x9f', '0xc2', '0xa2', '0xeb', '0x92', '0xf1', '0x4c', '0x27', '0x3c', '0x0']
